# Generated by Django 3.2 on 2024-04-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='email',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
