# Generated by Django 3.2 on 2024-04-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_details_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='email',
            field=models.CharField(max_length=120),
        ),
    ]
