# Generated by Django 3.2 on 2024-04-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_image',
            field=models.CharField(default='https://global.discourse-cdn.com/business4/uploads/inductiveautomation/original/2X/9/97d457372f6c14182b686ecfdf5d4067df5e9373.png', max_length=5000),
        ),
    ]
